#cloud-config

coreos:
  update:
    reboot-strategy: off
  units:
    - name: iptables-private.target
      content: |
        [Unit]
        Description=Group instantiated iptables-private services
        Requires=iptables-restore.service

        [Install]
        WantedBy=multi-user.target
      command: start
    - name: iptables-private@.service
      content: |
        [Unit]
        Description=Add iptables rule for the peers private IP
        After=iptables-restore.service

        [Service]
        Type=oneshot
        ExecStart=/sbin/iptables -w -A PRIVATE -p tcp -s %i -j ACCEPT

        [Install]
        WantedBy=iptables-private.target
write_files:
  - path: /var/lib/iptables/rules-save
    permissions: 0644
    owner: root:root
    content: |
      *filter
      :INPUT ACCEPT [0:0]
      :FORWARD DROP [0:0]
      :OUTPUT ACCEPT [0:0]
      -N PRIVATE
      -N PUBLIC
      -A INPUT -i lo -j ACCEPT
      -A INPUT -i eth0 -m conntrack --ctstate NEW -j PUBLIC
      -A INPUT -i eth0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
      -A INPUT -i eth1 -j PRIVATE
      -A INPUT -i docker0 -j ACCEPT
      -A INPUT -j DROP
      -A PUBLIC -p tcp -m tcp --dport 22 -j ACCEPT
      COMMIT
  - path: /etc/ssh/sshd_config
    permissions: 0600
    owner: root:root
    content: |
      # Use most defaults for sshd configuration.
      UsePrivilegeSeparation sandbox
      Subsystem sftp internal-sftp
      ClientAliveInterval 180
      UseDNS no

      PasswordAuthentication no
      ChallengeResponseAuthentication no
...
